const datamodel = [
  {
    dept: "Information technology",
    courses: "opration system , networking ,Ip1 , Ip2 , algorithm",

    questionCollectionList: [
      {
        year: 2015,
        questionList: [
          {
            question: "888the most popular sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badton",
            answer: "A",
          },
          {
            question: "What is the most 77popular sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most 88popular sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most popular88 sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most p the world?",
            op1: "eyball",
            op2: "all",
            op3: "nton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most popular7 sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most popular00 sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most popular sport 88 throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is th88e most popular sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most popular sport thro   ughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most popular sport throughout 00 the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most 333popular sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
        ],
      },
      {
        year: 2016,
        questionList: [
          {
            question: "What is the most popular sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "B",
          },
          {
            question: "What is the most popular sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "A",
          },
          {
            question: "What is the most popular sport throughout the world?",
            op1: "Volleyball",
            op2: "Football",
            op3: "Badminton",
            op4: "Badminton",
            answer: "C",
          },
        ],
      },
    ],
  },
];
export default datamodel;
